# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
dist: output/
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -X main.version="v{{.Version}}-{{.Date}}" 	-X main.commit="{{.FullCommit}}" -X main.date="{{.Date}}" -X main.branch="{{.Branch}}"
    main: ./cmd/app

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - config/config.yml
      - LICENSE
      - OPENSOURCE.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
    - "ghcr.io/ninehills/{{ .ProjectName }}:{{ .Version }}-{{ .ShortCommit }}"
    - "ghcr.io/ninehills/{{ .ProjectName }}:{{ .Version }}"
    - "ghcr.io/ninehills/{{ .ProjectName }}:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/amd64"
    extra_files:
    - config/config.yml
    - LICENSE
    - OPENSOURCE.md
  -
    goos: linux
    goarch: arm64
    image_templates:
    - "ghcr.io/ninehills/{{ .ProjectName }}:{{ .Version }}-{{ .ShortCommit }}-arm64"
    - "ghcr.io/ninehills/{{ .ProjectName }}:{{ .Version }}-arm64"
    - "ghcr.io/ninehills/{{ .ProjectName }}:latest-arm64"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"
    extra_files:
    - config/config.yml
    - LICENSE
    - OPENSOURCE.md