version: '3.9'
services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'app'
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: ./sql/schema
        target: /docker-entrypoint-initdb.d

  redis:
    container_name: redis
    image: redis:7
    ports:
      - 6379:6379

  app:
    container_name: app
    image: ghcr.io/ninehills/go-webapp-template:latest
    environment:
      MYSQL_DSN: 'root:pass@tcp(mysql:3306)/app?parseTime=true'
      REDIS_URL: 'redis://redis:6379/1'
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    environment:
      APP_HOST: "app:8080"
    depends_on:
      - app
