app:
  name: "go-webapp-template"
  debug: false
  superUser: "admin"
  superPassword: "admin!123"

http:
  port: "8080"

log:
  level: "debug"
  format: "text"
  noColor: false

mysql:
  dsn: "go_webapp:go_webapp@tcp(127.0.0.1:3306)/go_webapp?parseTime=true"
  connMaxLifetime: 180
  maxOpenConns: 100
  maxIdleConns: 100

redis:
  url: "redis://localhost:6379/1"
