app:
  name: "go-webapp-template"
  debug: false
  superUser: "admin"
  superPassword: "admin!123"

http:
  port: "8080"

log:
  level: "debug"
  format: "text"
  noColor: false

mysql:
  dsn: "root:pass@tcp(127.0.0.1:3306)/app?parseTime=true&timeout=30s&readTimeout=30s&writeTimeout=30s"
  connMaxLifetime: 180
  maxOpenConns: 10
  maxIdleConns: 10

redis:
  url: "redis://localhost:6379/0"
